//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProtegoPdf.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProtegoPdf.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An empty or invalid password was provided for this document..
        /// </summary>
        internal static string Operation_BadPassword_Description {
            get {
                return ResourceManager.GetString("Operation_BadPassword_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad_Password.
        /// </summary>
        internal static string Operation_BadPassword_Type {
            get {
                return ResourceManager.GetString("Operation_BadPassword_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to access the requested file..
        /// </summary>
        internal static string Operation_FileAccessError_Description {
            get {
                return ResourceManager.GetString("Operation_FileAccessError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File_Access_Error.
        /// </summary>
        internal static string Operation_FileAccessError_Type {
            get {
                return ResourceManager.GetString("Operation_FileAccessError_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A general exception has been thrown by the target invocation..
        /// </summary>
        internal static string Operation_GeneralError_Description {
            get {
                return ResourceManager.GetString("Operation_GeneralError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General_Error.
        /// </summary>
        internal static string Operation_GeneralError_Type {
            get {
                return ResourceManager.GetString("Operation_GeneralError_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create file due to insuffient permissions..
        /// </summary>
        internal static string Operation_InsufficientPermissions_Description {
            get {
                return ResourceManager.GetString("Operation_InsufficientPermissions_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient_Permissions.
        /// </summary>
        internal static string Operation_InsufficientPermissions_Type {
            get {
                return ResourceManager.GetString("Operation_InsufficientPermissions_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given Action is not a valid operation.
        /// </summary>
        internal static string Operation_InvalidAction_Description {
            get {
                return ResourceManager.GetString("Operation_InvalidAction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid_Action.
        /// </summary>
        internal static string Operation_InvalidAction_Type {
            get {
                return ResourceManager.GetString("Operation_InvalidAction_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An empty or invalid argument was supplied to this operation..
        /// </summary>
        internal static string Operation_InvalidArgument_Description {
            get {
                return ResourceManager.GetString("Operation_InvalidArgument_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid_Argument.
        /// </summary>
        internal static string Operation_InvalidArgument_Type {
            get {
                return ResourceManager.GetString("Operation_InvalidArgument_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given file is not a pdf file or the file is corrupted..
        /// </summary>
        internal static string Operation_NotAPdfDocument_Description {
            get {
                return ResourceManager.GetString("Operation_NotAPdfDocument_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not_A_Pdf_Document.
        /// </summary>
        internal static string Operation_NotAPdfDocument_Type {
            get {
                return ResourceManager.GetString("Operation_NotAPdfDocument_Type", resourceCulture);
            }
        }
    }
}
